language: clojure
dist: trusty
lein: lein
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.cache/pip"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.0/elasticsearch-2.4.0.deb
    && sudo dpkg -i --force-confnew elasticsearch-2.4.0.deb && sudo service elasticsearch
    restart
  - mkdir -p $HOME/.lein
  - touch $HOME/.lein/profiles.clj
  - echo '{:user {:dependencies [[org.clojure/clojure "1.8.0"] [potemkin "0.4.5"]]}}'
    > $HOME/.lein/profiles.clj
before_script:
  - psql -c 'CREATE DATABASE kulu_backend_test;' -U postgres
  - psql -d kulu_backend_test -c 'CREATE extension "uuid-ossp";' -U postgres
  - sleep 10
env:
  global:
    - PGPORT = 6666 DATABASE_URL = postgres://$USER:@localhost:$PGPORT/kulu_backend_test
script: lein test
branches:
  only:
    - ansible
notifications:
  email:
    on_success: never
    on_failure: never
services:
  - elasticsearch
addons:
  postgresql: '9.6'
  ssh_known_hosts: 165.22.213.15
  apt:
    packages:
      - sshpass
before_deploy:
  - sudo pip install ansible
  - openssl aes-256-cbc -K $encrypted_3c3c8465fa13_key -iv $encrypted_3c3c8465fa13_iv
    -in deploy_key.enc -out $HOME/deploy_key -d
  - chmod 600 $HOME/deploy_key
  - eval `ssh-agent -s`
  - ssh-add $HOME/deploy_key
  - lein clean
  - lein uberjar
  - scp $HOME/build/nilenso/kulu-backend/target/kulu-backend-0.1.0-SNAPSHOT-standalone.jar $DEPLOY_USER@$DEPLOY_TARGET:~/
deploy:
  provider: script
  script: ansible-playbook ansible/kulu.yml -i ansible/inventory/hosts -u $DEPLOY_USER
    -e "ansible_sudo_pass=$ANSIBLE_SUDO_PASS" --private-key $HOME/deploy_key
  on:
    branch: ansible
